### ISSUE TITLE
pos-js is missing

### ISSUE THREAD

**Issue by PSeitz** [nhunzaker/speakeasy#5]
Hi,

pos-js is just an emtpy folder

**Comment by rorydonohue** [comment]
I get this error when trying to require the module: 

```
Error: Cannot find module './pos-js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/roryd/Desktop/clients/barclays/speakeasy/lib/classify/index.js:15:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Unfortunately I can't try this package out due to this. 

Any pointers ?

**Comment by rorydonohue** [comment]
Ah it seems to be this module: https://www.npmjs.com/package/pos - just requires a "npm install pos" and changing the include to be the right path.

**Comment by nhunzaker** [comment]
Fantastic... I'll check it out.

**Comment by nhunzaker** [comment]
Okay. A while back, I maintained my own fork of `pos` that added some additional logic to help distinguish the subject of a statement (at least those are the tests that fail when I use `pos-js` instead of the one packaged with `speakeasy-nlp`). I've re-introduced this as a part of the codebase and everything should check out.

Now I'm going to determine just how different my `pos-js` is from the latest work over at https://www.npmjs.com/package/pos.

All the same, you should now be able to pull down the repo and use `speakeasy-nlp` without a problem.

**Comment by nhunzaker** [comment]
I'm going to go ahead and close this. The accident here was that I deleted my fork of `pos-js` without considering that `speakeasy-nlp` was using it. I just set up continuous integration to help prevent accidents like this from occuring in the future.
